FROM node:20-bullseye-slim

RUN apt-get update && apt-get install -y dnsutils procps \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV PNPM_HOME="/pnpm"

ENV PATH="$PNPM_HOME:$PATH"

RUN npm i -g pnpm 

RUN pnpm config set auto-install-peers true

WORKDIR /app

COPY . .

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm i --frozen-lockfile
